-- Chatify Auth Tables Migration
-- Run this in Supabase SQL Editor

-- 1. Users table
CREATE TABLE IF NOT EXISTS chatify_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'COLLABORATOR',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. User-Store access (many-to-many)
CREATE TABLE IF NOT EXISTS user_store_access (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES chatify_users(id) ON DELETE CASCADE,
  store_id UUID REFERENCES stores(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, store_id)
);

-- 3. Seed SUPER_ADMIN (password will be set via API on first login)
-- The bcrypt hash for '+shopieasy.040530*' will be generated by the login endpoint
